spring:
  application:
    name: competition-feign
  cloud:
     config:
          lable: master
          profile: dev
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
debug: true