spring:
  application:
    name: competition-server-usercenter
  cloud:
     config:
          lable: master
          profile: dev
  port: 8082
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: aloe123
    url: jdbc:mysql://127.0.0.1/usercenter?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
debug: true