eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: competition-zuul
  cloud:
    config:
      lable: master
      profile: dev

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
zuul:
  routes:
    usercenter:
      path: /usercenter/**
      serviceId: competition-server-usercenter
    api-a:
      path: /usercenterribbon/**
      serviceId: competition-ribbon
    api-b:
      path: /usercenterfeign/**
      serviceId: competition-feign

#          department:
#            path: /department/**
#            serviceId: department-service
#          employee:
#            path: /employee/**
#            serviceId: employee-service
#          organization:
#            path: /organization/**
#            serviceId: organization-service
#这是一些案例，用于参考使用